# Generated by Django 4.1.7 on 2023-03-13 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedroomListing',
            fields=[
                ('listing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('price_new', models.IntegerField(blank=True)),
                ('price_old', models.IntegerField(blank=True)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assembled_size', models.CharField(max_length=200)),
                ('structured_frame', models.CharField(max_length=200)),
                ('assembly', models.CharField(max_length=200)),
                ('made_in_location', models.CharField(max_length=200)),
                ('offer', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
